### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by giriarteS** [lanzen/CREST#1]
I have tried to install CREST, but I get this error. 
Creating directory '/Users/giri/CREST/LCAClassifier/bin'.
Creating directory '/Users/giri/CREST/LCAClassifier/parts'.
Creating directory '/Users/giri/CREST/LCAClassifier/eggs'.
Creating directory '/Users/giri/CREST/LCAClassifier/develop-eggs'.
Generated script '/Users/giri/CREST/LCAClassifier/bin/buildout'.
/Users/giri/CREST/LCAClassifier/eggs/setuptools-18.4-py2.7.egg/pkg_resources/**init**.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Getting distribution for 'zc.buildout>=2.2.1'.
Got zc.buildout 2.4.5.
Upgraded:
  zc.buildout version 2.4.5;
restarting.
Generated script '/Users/giri/CREST/LCAClassifier/bin/buildout'.
Develop: '/Users/giri/CREST/LCAClassifier/.'
Getting distribution for 'zc.recipe.testrunner'.
zip_safe flag not set; analyzing archive contents...
Got zc.recipe.testrunner 2.0.0.
Getting distribution for 'zc.recipe.egg>=1.2.0,>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Getting distribution for 'zope.testrunner'.
package init file 'src/zope/testrunner/tests/testrunner-ex/**init**.py' not found (or not a regular file)
Got zope.testrunner 4.4.9.
Getting distribution for 'zope.interface'.
warning: no previously-included files matching '_.dll' found anywhere in distribution
warning: no previously-included files matching '_.pyc' found anywhere in distribution
warning: no previously-included files matching '_.pyo' found anywhere in distribution
warning: no previously-included files matching '_.so' found anywhere in distribution
warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
Got zope.interface 4.1.3.
Getting distribution for 'zope.exceptions'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
Got zope.exceptions 4.0.8.
Getting distribution for 'z3c.recipe.template'.
Got z3c.recipe.template 0.1.
Getting distribution for 'z3c.recipe.mkdir'.
Got z3c.recipe.mkdir 0.6.
Getting distribution for 'hexagonit.recipe.download'.
Got hexagonit.recipe.download 1.7.
Getting distribution for 'pb.recipes.pydev'.
Got pb.recipes.pydev 0.4.5.
Installing test.
Getting distribution for 'six'.
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__
Got six 1.10.0.
Getting distribution for 'biom-format'.
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '_.pyc' found anywhere in distribution
warning: no previously-included files matching '_.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
biom/_filter.c:258:10: fatal error: 'numpy/arrayobject.h' file not found
# include "numpy/arrayobject.h"

```
     ^
```

1 error generated.
error: Setup script exited with error: command 'clang' failed with exit status 1
An error occurred when trying to install biom-format 2.1.4. Look above this message for any errors that were output by easy_install.
While:
  Installing test.
  Getting distribution for 'biom-format'.
Error: Couldn't install: biom-format 2.1.4

I have biom-format 2.1.4 already. 
pip list | grep biom-format
biom-format (2.1.4)

any idea?

**Comment by lanzen** [comment]
Hi,
This seems to be a new issue, with biom-format. It does not matter that you have it because it needs to be installed in the site-packages of the LCAClassifier. We are also having issue with zc.buildout which makes it impossible at the moment to test this out on my machine, but I am rewriting parts of LCAClassifier from scratch to be released with a major update of the program and database.

Anyway, try to simply add the following line at the end of buildout.cfg:
biom-format = 2.0.1

**Comment by lanzen** [comment]
I have now locked biom-format to an older version after looking at a similar installation problem from forced installation of numpy although it should not be necessary. This seems to be occuring whenever biom-format >2.0 is installed. Please try to update the source release to the latest version (git pull) and try to install again. I will include this in a minor bug fix release asap.

**Comment by sara45450** [comment]
Hi
i can not install ,i update all files on LCAClassifier.
./install.sh
Traceback (most recent call last):
File "bootstrap.py", line 88, in
exec(urlopen('https://bootstrap.pypa.io/ez_setup.py').read(), ez)
File "", line 24, in
ImportError: cannot import name 'log'
./install.sh: line 2: bin/buildout: No such file or directory

**Comment by lanzen** [comment]
Hi,
I am not sure I understand this. Can you send me the version of bootstrap.py you use because line 88 does not  seem to correspond to the one of CREST. Are you sure this is not during the installation of one of the dependencies of CREST?

On the other hand, I tried re-installing CREST in Ubuntu 16.04 for me and I have found it no longer works, because of a new update of zc.buildout, I think. It is now impossible to use the old version becuase they do not allow it from other components and since the new one also does not work I cannot quite figure out what to do with this. I will keep you updated.

Best wishes,
Anders

**Comment by sara45450** [comment]
Thank you
What distribution do you recommend for Linux and Python?

**Comment by lanzen** [comment]
For python 2.7. For Ubuntu 16.04 used to be the only one tested but it
doesn't help. The updates from zc.buildout were never backwards compatible
and in the end I had to lock it to an old version, but it seems now that is
also broken, due to the latest update. Try it though, and I promise to look
at this as soon as I can.
