### ISSUE TITLE
Update to latest Silva.

### ISSUE THREAD

**Issue by xapple** [lanzen/CREST#3]
It seems like CREST or LCACLASSIFIER (it seems like your product uses two names interchangeably) uses the "silvamod" database by default. If I go to your user guide, the link to the page that describes it is dead. But I remember it was already there in the first version. Do you have any plans to update to the latest version ?

**Comment by lanzen** [comment]
Hi,

I am not sure where you found the dead link so I cannot fix it. The user guide should be visible directly under the GitHub project page and also linked from the Wiki. The address is https://github.com/lanzen/CREST/wiki/CREST-User-guide

We are currently working on a new version which will include an updated SilvaMod database (based on the SilvaRef v123 release - this is long overdue since SilvaMod is now based on v106 from 2012 but better late than never, I hope).  The new version should also be considerably faster and offer better support for working with a large number of samples. I am not sure when we can release this but it does not seem likely that it will be before the autumn.

Best,
Anders

**Comment by xapple** [comment]
It's good you moved to github, but you still have all the old websites up:
- http://apps.cbu.uib.no/crest/index
- http://lcaclassifier.googlecode.com
- https://www.ii.uib.no/trac/LCAClassifier/
- https://code.google.com/archive/p/lcaclassifier/wikis/Userguide.wiki
- http://services.cbu.uib.no/supplementary/crest
- https://github.com/lanzen/CREST

It's a _huge_ mess with duplication and outdated text all over. And when you search with google, those are the ones that come up fist. In addition to the double naming of your project, all this makes lots of confusion for the poor user.

The dead link I was referring to was actually on the copy number 3 of your documentation, on this page, on the first line:

https://www.ii.uib.no/trac/LCAClassifier/wiki/Userguide

I'll probably try to add the normal Silva 123 database in the "flatdb" directory to use it none the less. Any reasons for which this would be a bad idea ?

**Comment by lanzen** [comment]
Thank you for making me aware about this. I have asked for the old version at 
https://www.ii.uib.no/trac/LCAClassifier/ to be taken down and will try to shut down the Google Code repo. The others make sense, since http://services.cbu.uib.no/supplementary/crest are used for hosting the large database files that I believe cannot be hosted easily and freely at Github (?), and http://apps.cbu.uib.no/crest/index hosts the CREST Web server which is independent from the standalone version hosted at Github. Although I don't have the resources to support it, it is still used and works fine so I am reluctant to take it down.

You cannot use alignments to the normal Silva123 database with the LCAClassifier, since it will not understand the taxonomical hierarchy. You would have to export a so-called NDS (tab-separated file) from ARB and use it to generate a new .tre and .map file for LCAClassifier, following the instructions here: https://github.com/lanzen/CREST/wiki/CREST-User-guide#constructing-a-custom-reference-database

Best,
Anders

**Comment by xapple** [comment]
Thanks for your answers !

**Comment by xapple** [comment]
So I looked at the guide. It seems like three files are needed. `fasta`, `tre` and `map`. But the guide suggests that the fasta file should actually be an alignment-fasta and not just a normal flat fasta ? This seem strange to me. The fasta file is used for BLASTing, why would you want an alignment ?

**Comment by lanzen** [comment]
I cannot find it written anywhere that the sequences should be aligned. It is correct that you should export just only the unaligned FASTA. However:

> Sequences of the reference marker genes in the alignment, in FASTA format (sequences.fasta in the example below). It is important that the sequences are cropped so that stretches of unaligned sequence is not included. Such sequences may bias the alignments during classification. In ARB, this can be done by using a positional filter when exporting sequences.

This means that you need to crop sequences using the multiple guidetree-alignment that forms the basis for the taxonomic reference database, to make sure that only the SSU rRNA gene and nothing else (unaligned) is exported.

**Comment by xapple** [comment]
If you look at the first paragraph of the tutorial from making a "custom reference database" it says this

> Sequences of the reference marker genes in the alignment, in FASTA format (sequences.fasta in the example below). It is important that the sequences are cropped so that stretches of unaligned sequence is not included. Such sequences may bias the alignments during classification. In ARB, this can be done by using a positional filter when exporting sequences.

That contains the work unaligned or alignement three times. If it's supposed to be a flat fasta file, say so and be clear to the user.

In the end I spent about two hours and a half trying to get Silva version 123 to play nice in CREST and did not succeed. I'm maybe not the best bioinformatician in the world, but it's fair to say you have made this process very hard.

I had to switch to the mothur wang-method classification sadly.

I have documented what I did in the form of a bash script (starting from the installation of CREST).
Of course the part that you do manually in ARB is not currently documented.
Maybe you can make this better and figure out where the problem is ?

Installation:

```
mkdir -p ~/test

cd ~/test
wget https://github.com/lanzen/CREST/archive/2.0.4.zip
unzip 2.0.4.zip
cd CREST-*
mv LCAClassifier ~/programs/lca_classifier
cd ~/programs/lca_classifier
python ./bootstrap.py -v 2.2.1
bin/buildout

cd ~/bin
ln -s ~/programs/lca_classifier/bin/classify classify

cd ~/programs/lca_classifier/bin/
vim classify
# You have to comment out the numpy line
```

Silva database:

```
### Guide to making a new SILVA database for CREST ###

# Download database from the SILVA archive (on computer that has ARB) #
mkdir ~/databases/silva_123
cd ~/databases/silva_123
wget http://www.arb-silva.de/fileadmin/silva_databases/release_123/ARB_files/SSURef_NR99_123_SILVA_12_07_15_opt.arb.tgz
tar zxf SSURef_NR99_123_SILVA_12_07_15_opt.arb.tgz

# See https://github.com/lanzen/CREST/wiki/CREST-User-guide#constructing-a-custom-reference-database

# Transfer files from the computer that has ARB installed to here #
rsync -avz --progress /home/alexe/glob/databases/silva_123/silva_123.fasta ~/databases/silva123/
rsync -avz --progress /home/alexe/glob/databases/silva_123/silva_123.nds ~/databases/silva123/

# Change RNA to DNA (ARB outputs Uracil)
fasta_U_to_T < ~/databases/silva123/silva_123.fasta > ~/databases/silva123/silva_123_T.fasta

# Create empty file as suggested above in 3. #
touch ~/databases/silva123/MCF.txt

# Swap two columns #
cd ~/programs/lca_classifier/src/
vim arbor.py

# fix arbor.py at line 100 to
# taxonomy = parts[2]
# ncbi_name = parts[1]

# Run it #
python LCAClassifier/nds2CREST.py ~/databases/silva123/silva_123.fasta ~/databases/silva123/MCF.txt ~/databases/silva123/silva_123.nds
```

It didnt output an error message, instead it just never completed. Maybe you could make available a simple script that could add the current Silva v123 to CREST ? Even without the taxonomic modifications, that would be great.

**Comment by lanzen** [comment]
Hi,

I am sorry that I did not write the documentation more clearly. Exporting the FASTA file and tab-separated text correctly using ARB from Silva is extremely tricky. The problem is that what I wrote in the documentation is important - if you include stretches of sequence that are unaligned in the Silva alignment, then there is a high risk for false positive assignments with metatranscriptome or -genome data (although for amplicons inside the SSU rRNA gene it should not matter). Since several complicated settings have to be done in ARB and several commands run that are only available from the GUI, it is probably not possible to write a script for this purpose. However, I will make a new export myself as art of the update process in the next couple of weeks and I can share this with you and keep you updated. I will also take that opportunity to improve the documentation.

What is the numpy line you refer to? This is normally not an issue, but if it causes an error for you and if that line is really importing a something that is not used then I will of course remove it and make a minor update.

Best,
Anders

**Comment by xapple** [comment]
OK, looking forward to seeing the new version then ! Thanks for your help in any case !

The numpy thing is what I was talking about here: https://github.com/lanzen/CREST/issues/2

Seems like CREST comes with its own numpy, but when it is built it links against other libraries, or maybe when it's imported it tries to import the wrong one ?

At least after commenting out this line, everything worked again:

```
import sys
sys.path[0:0] = [
  '/home/lucas/programs/lca_classifier/src',
  '/home/lucas/programs/lca_classifier/eggs/biom_format-2.1.5-py2.7-linux-x86_64.egg',
#  '/home/lucas/programs/lca_classifier/eggs/numpy-1.6.2-py2.7-linux-x86_64.egg',
  '/home/lucas/programs/lca_classifier/eggs/biopython-1.66-py2.7-linux-x86_64.egg',
  '/home/lucas/programs/lca_classifier/eggs/setuptools-21.0.0-py2.7.egg',
  '/home/lucas/programs/lca_classifier/eggs/pyqi-0.3.2-py2.7.egg',
  '/home/lucas/programs/lca_classifier/eggs/scipy-0.17.0-py2.7-linux-x86_64.egg',
  '/home/lucas/programs/lca_classifier/eggs/future-0.15.2-py2.7.egg',
  '/home/lucas/programs/lca_classifier/eggs/click-6.6-py2.7.egg',
  ]
```

**Comment by brwnj** [comment]
I see you're busy working on the code, but I'm personally more interested in a highly curated version of SILVA 123 or 128. Any chance you're also working on that?

**Comment by lanzen** [comment]
Hi Joe,
I am indeed working on an update of the database to SILVA v128, but since this database is larger it was necessary to optimise the program, while also getting rid of some serious bugs, like inconsistency between taxonomic ranks when a strict Linnean rank structure is not available because a particular rank is missing - a common problem with the existing eukaryotic taxonomy.

Two non-curated version of Silva v123 are already available in case you are interested in helping to test it, either for the new or the older v2 of the LCAClassifier.  Please let me know.

Best,
Anders
