### ISSUE TITLE
Read population extraction

### ISSUE THREAD

**Issue by felixeye** [lanzen/CREST#5]
Hi,
I would like to thank you for the nice job that you did here.
While using the version 3.0.5 I noticed 2 things:
the documentation is a little outdated (I am not sure)
The second one is **classify.py:668** `readPopulation = int(seq_record.id[seq_record.id.find("size=") + len("size="):-1])`
This line generates the following error: 
> ValueError: invalid literal for int() with base 10: ''

Which happens because the last character of the string is chopped off I believe.
Once again thank you for your work.

**Comment by lanzen** [comment]
Hi Felix,

I am happy that you like CREST and find it useful!

You are absolutely right that the documentation is a little outdated. I have been meaning to update it and also write up the new version, which is basically a re-implementation and an update to make .map and .tre files smaller, thus reducing memory demands. Apart from the new SilvaMod and amoA database. However, I have no dedicated time to spend on CREST and therefore things sometimes move slowly. Can you tell me if you find any specific errors in the documentation because that would be helpful!

I am not sure how the the line you refer can cause the ValueError. The last character should always be a line break. Try to insert one as the very last character of the FASTA-file you gave as an input, if that is what you did (and note that all text-files have to end with a newline character as per GNU/Linux standard but if this is what caused the crash then I will of course fix it - I just want to confirm it first). Does that help? Please let me know so that I can better figure out what is happening.

Best,
Anders

**Comment by lanzen** [comment]
...I forgot to add that it is strange if the FASTA-header does not end with a line break. That means your FASTA-file ends with something like:
>OTU999 size=1
Followed by no sequence. Is this really the case? Or is it the BLAST  XML file? If, for example, you have run the LCAClassifier using:
classify -i otus.fasta -t otu_table.csv otus_vs_silvamod128.xml

..then can you send the output of:
tail otus.fasta
tail otus_vs_silvamod128.xml

Best,
Anders

**Comment by felixeye** [comment]
Hi Anders,
thank you very much for your fast answer, unfortunately I have not got enough time to explore but I will run a test tomorrow and send you the resulting files if needed tomorrow.

It's true that the FASTA header should have a line break as last character. As far as I can see the FASTA file seems correctly formatted.
SeqIO.parse could possibly be taking away the trailing break lines and '\r' characters from the id attribute at least.

With kind regards

**Comment by lanzen** [comment]
Could you send me the OTU table and FASTA file that you used when you got
the error so that I can have a look at it?

**Comment by felixeye** [comment]
Sorry for being silent so long,

I do not use an OTU table but the OTU population is given in the header for each OTU.
I have also tried adding a last character ';' at the end of the header but that did not work neither.

I hope that can help, if you need any additional information please let me know.

[test_data_on_silvamod128.blastxml.gz](https://github.com/lanzen/CREST/files/1706916/test_data_on_silvamod128.blastxml.gz)
[test_data_on_silvamod128.fasta.gz](https://github.com/lanzen/CREST/files/1706923/test_data_on_silvamod128.fasta.gz)

**Comment by lanzen** [comment]
Hi Felix,

Nothing is wrong with your FASTA file and you were right about the bug
being caused by the -1. I have now removed it and it seems to work. Please
use git to update your version and then I will make a new release as soon
as you can confirm that you get the expected result.

Cheers,
Anders

**Comment by felixeye** [comment]
Greaaaat! It went fast,
I just tested it and... it works well.
Thank you very much for your help.

With kind regards,
Felix
